const NIFTY_50_STOCKS = [
  { symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Energy', exchange: 'NSE' },
  { symbol: 'TCS', name: 'Tata Consultancy Services', sector: 'IT', exchange: 'NSE' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'INFY', name: 'Infosys', sector: 'IT', exchange: 'NSE' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'FMCG', exchange: 'NSE' },
  { symbol: 'ITC', name: 'ITC Limited', sector: 'FMCG', exchange: 'NSE' },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecom', exchange: 'NSE' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'LT', name: 'Larsen & Toubro', sector: 'Infrastructure', exchange: 'NSE' },
  { symbol: 'AXISBANK', name: 'Axis Bank', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints', sector: 'Consumer', exchange: 'NSE' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki', sector: 'Automobile', exchange: 'NSE' },
  { symbol: 'TITAN', name: 'Titan Company', sector: 'Consumer', exchange: 'NSE' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical', sector: 'Pharma', exchange: 'NSE' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', sector: 'Finance', exchange: 'NSE' },
  { symbol: 'WIPRO', name: 'Wipro', sector: 'IT', exchange: 'NSE' },
  { symbol: 'HCLTECH', name: 'HCL Technologies', sector: 'IT', exchange: 'NSE' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', sector: 'Automobile', exchange: 'NSE' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', sector: 'Cement', exchange: 'NSE' },
  { symbol: 'NESTLEIND', name: 'Nestle India', sector: 'FMCG', exchange: 'NSE' },
  { symbol: 'NTPC', name: 'NTPC Limited', sector: 'Power', exchange: 'NSE' },
  { symbol: 'POWERGRID', name: 'Power Grid Corp', sector: 'Power', exchange: 'NSE' },
  { symbol: 'ONGC', name: 'Oil & Natural Gas Corp', sector: 'Energy', exchange: 'NSE' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra', sector: 'Automobile', exchange: 'NSE' },
  { symbol: 'TATASTEEL', name: 'Tata Steel', sector: 'Metals', exchange: 'NSE' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel', sector: 'Metals', exchange: 'NSE' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', sector: 'Conglomerate', exchange: 'NSE' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports', sector: 'Infrastructure', exchange: 'NSE' },
  { symbol: 'TECHM', name: 'Tech Mahindra', sector: 'IT', exchange: 'NSE' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', sector: 'Finance', exchange: 'NSE' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life Insurance', sector: 'Insurance', exchange: 'NSE' },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance', sector: 'Insurance', exchange: 'NSE' },
  { symbol: 'DIVISLAB', name: 'Divis Laboratories', sector: 'Pharma', exchange: 'NSE' },
  { symbol: 'DRREDDY', name: 'Dr. Reddys Laboratories', sector: 'Pharma', exchange: 'NSE' },
  { symbol: 'CIPLA', name: 'Cipla', sector: 'Pharma', exchange: 'NSE' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', sector: 'Healthcare', exchange: 'NSE' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors', sector: 'Automobile', exchange: 'NSE' },
  { symbol: 'GRASIM', name: 'Grasim Industries', sector: 'Cement', exchange: 'NSE' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank', sector: 'Banking', exchange: 'NSE' },
  { symbol: 'BRITANNIA', name: 'Britannia Industries', sector: 'FMCG', exchange: 'NSE' },
  { symbol: 'COALINDIA', name: 'Coal India', sector: 'Mining', exchange: 'NSE' },
  { symbol: 'BPCL', name: 'Bharat Petroleum', sector: 'Energy', exchange: 'NSE' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products', sector: 'FMCG', exchange: 'NSE' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', sector: 'Automobile', exchange: 'NSE' },
  { symbol: 'HINDALCO', name: 'Hindalco Industries', sector: 'Metals', exchange: 'NSE' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto', sector: 'Automobile', exchange: 'NSE' },
  { symbol: 'WIPRO', name: 'Wipro Limited', sector: 'IT', exchange: 'NSE' },
  { symbol: 'UPL', name: 'UPL Limited', sector: 'Chemicals', exchange: 'NSE' },
];

const SECTORS = [
  'Energy', 'IT', 'Banking', 'FMCG', 'Telecom', 'Infrastructure',
  'Consumer', 'Automobile', 'Pharma', 'Finance', 'Cement', 'Power',
  'Metals', 'Conglomerate', 'Insurance', 'Healthcare', 'Mining', 'Chemicals',
];

module.exports = { NIFTY_50_STOCKS, SECTORS };
