const NIFTY_50_STOCKS = [
  { symbol: 'RELIANCE', name: 'Reliance Industries', sector: 'Energy' },
  { symbol: 'TCS', name: 'Tata Consultancy Services', sector: 'IT' },
  { symbol: 'HDFCBANK', name: 'HDFC Bank', sector: 'Banking' },
  { symbol: 'INFY', name: 'Infosys', sector: 'IT' },
  { symbol: 'ICICIBANK', name: 'ICICI Bank', sector: 'Banking' },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever', sector: 'FMCG' },
  { symbol: 'ITC', name: 'ITC', sector: 'FMCG' },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking' },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel', sector: 'Telecom' },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank', sector: 'Banking' },
  { symbol: 'LT', name: 'Larsen & Toubro', sector: 'Infrastructure' },
  { symbol: 'AXISBANK', name: 'Axis Bank', sector: 'Banking' },
  { symbol: 'ASIANPAINT', name: 'Asian Paints', sector: 'Paints' },
  { symbol: 'MARUTI', name: 'Maruti Suzuki', sector: 'Automobile' },
  { symbol: 'TITAN', name: 'Titan Company', sector: 'Consumer' },
  { symbol: 'SUNPHARMA', name: 'Sun Pharma', sector: 'Pharma' },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance', sector: 'Finance' },
  { symbol: 'WIPRO', name: 'Wipro', sector: 'IT' },
  { symbol: 'HCLTECH', name: 'HCL Technologies', sector: 'IT' },
  { symbol: 'TATAMOTORS', name: 'Tata Motors', sector: 'Automobile' },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement', sector: 'Cement' },
  { symbol: 'NESTLEIND', name: 'Nestle India', sector: 'FMCG' },
  { symbol: 'NTPC', name: 'NTPC', sector: 'Power' },
  { symbol: 'POWERGRID', name: 'Power Grid', sector: 'Power' },
  { symbol: 'ONGC', name: 'ONGC', sector: 'Energy' },
  { symbol: 'M&M', name: 'Mahindra & Mahindra', sector: 'Automobile' },
  { symbol: 'TATASTEEL', name: 'Tata Steel', sector: 'Metals' },
  { symbol: 'JSWSTEEL', name: 'JSW Steel', sector: 'Metals' },
  { symbol: 'ADANIENT', name: 'Adani Enterprises', sector: 'Conglomerate' },
  { symbol: 'ADANIPORTS', name: 'Adani Ports', sector: 'Infrastructure' },
  { symbol: 'TECHM', name: 'Tech Mahindra', sector: 'IT' },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv', sector: 'Finance' },
  { symbol: 'HDFCLIFE', name: 'HDFC Life', sector: 'Insurance' },
  { symbol: 'SBILIFE', name: 'SBI Life', sector: 'Insurance' },
  { symbol: 'DIVISLAB', name: 'Divi\'s Labs', sector: 'Pharma' },
  { symbol: 'DRREDDY', name: 'Dr Reddy\'s', sector: 'Pharma' },
  { symbol: 'CIPLA', name: 'Cipla', sector: 'Pharma' },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals', sector: 'Healthcare' },
  { symbol: 'EICHERMOT', name: 'Eicher Motors', sector: 'Automobile' },
  { symbol: 'GRASIM', name: 'Grasim', sector: 'Cement' },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank', sector: 'Banking' },
  { symbol: 'BRITANNIA', name: 'Britannia', sector: 'FMCG' },
  { symbol: 'COALINDIA', name: 'Coal India', sector: 'Mining' },
  { symbol: 'BPCL', name: 'BPCL', sector: 'Energy' },
  { symbol: 'TATACONSUM', name: 'Tata Consumer', sector: 'FMCG' },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp', sector: 'Automobile' },
  { symbol: 'HINDALCO', name: 'Hindalco', sector: 'Metals' },
  { symbol: 'BAJAJ-AUTO', name: 'Bajaj Auto', sector: 'Automobile' },
  { symbol: 'UPL', name: 'UPL', sector: 'Chemicals' },
];

module.exports = { NIFTY_50_STOCKS };
